
language: shell
os: linux
dist: bionic


addons:
  apt:
    packages:
    - curl
    - ffmpeg
    - lftp
    - sed
    - wget
    
script:
    - sudo sh -c "mkdir /video && chown $(whoami):$(whoami) /video" && cd /video
    - C44=C44.mp4
    - C45=C45.mp4
    - ffmpeg -i "https://proxy-19.nyc.dailymotion.com/sec(eONP7ymDWd7NtSmSfJBos-cxHob6vyE5YmqjVsNln_nDUY3CkTwy1cgAD_yJTrXFExDOVElJ-bbPSHRO9JtwF-rkDB5bU0o6EARuO5nvP2A)/video/942/543/481345249_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "$C44" 
    - ffmpeg -i "https://proxy-14.nyc.dailymotion.com/sec(iAXo1UrOAO1i5LjM3lZ0hgebR_265AsBveIgslitJecCgExHGXSNMx9moCV0DlSjcQ83j4Okfriy4lAygOg4wcYUpmFo7wBWoYkvIRsnv2M)/video/352/543/481345253_mp4_h264_aac_hd.m3u8" -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 23 "$C45" 
    - curl https://bashupload.com/$C44 --data-binary @$C44
    - curl https://bashupload.com/$C45 --data-binary @$C45
